### ISSUE TITLE
compose/edit messages in an external editor

### ISSUE THREAD

**Issue by japanoise** [Calamitous/iris#2]
Hi, I'm loving Iris :) I'd like to use my system editor to compose messages. Implementation should be pretty simple, create a tempfile for the user's message, then open it up with their editor:

1. `$VISUAL`, if set
2. `$EDITOR`, if set
3. `nano` or `vi`

Thanks!

**Comment by Calamitous** [comment]
Iris now uses `$EDITOR` for composing and editing messages, as of version 1.1.0.  Let me know how it works for you!
