### ISSUE TITLE
add info to help on how to quit!

### ISSUE THREAD

**Issue by lee2sman** [Calamitous/iris#6]
Hello, I'm a big fan of iris. One suggestion: every time I try to quit iris I struggle. I try ```exit``` (nothing) and always eventually do Control-C, which force escapes. Today I discovered ```q``` seems to quit cleanly. Can you add that command to the ```help``` file?

**Comment by Calamitous** [comment]
Hey, thanks for opening an issue!  This is a great idea.  I merged your PR, thanks so much for your help!
