### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by ffuentese** [Calamitous/iris#9]
Is it possible to make Iris support special characters? I mean accents or non English letters. i.e. we speak Spanish and ñ or accented letters don't work.
```

reply~> probando ñá
/usr/local/bin/iris:829:in `=~': invalid byte sequence in UTF-8 (ArgumentError)
	from /usr/local/bin/iris:829:in `!~'
	from /usr/local/bin/iris:829:in `replying_handler'
	from /usr/local/bin/iris:890:in `handle'
	from /usr/local/bin/iris:935:in `initialize'
	from /usr/local/bin/iris:917:in `new'
	from /usr/local/bin/iris:917:in `start'
	from /usr/local/bin/iris:1082:in `initialize'
	from /usr/local/bin/iris:1142:in `new'
	from /usr/local/bin/iris:1142:in `<main>'
```

**Comment by Calamitous** [comment]
I wasn't able to replicate this issue directly.  Iris _should_ be able to handle any UTF-8 characters.  I've wrapped a little more error handling around the line parser in 1.0.12, so this should fix the issue.  If not please re-open, or add a new ticket and we'll chase this problem down.
